#!/bin/sh
echo "Importing Mesa County Fleet Maintenance .csv files"
docker run -t --volumes-from ses_app -w="/var/www" --link ses_mysql:mysql --name "ses_app_cron" ses_app php artisan energy-stat:csv-import -d ftp-uploads/Mesa_County_Fleet_Maintenance_Shop_001EC6051AEB mc_fleet_maintenance
docker rm ses_app_cron
